### ISSUE TITLE
Impossible to select compose file

### ISSUE THREAD

**Issue by loranger** [alanzanattadev/atom-docker#1]
Hello,

I'd love to use your package in my Atom and speedup my developments, but I can't use my existing `docker-compose.yml` file.
As you can see on [this screenshot](http://take.ms/T1550), there is a TypeError :
```
TypeError: Cannot convert undefined or null to object
```

Is there a particular setup I did miss ?

**Comment by loranger** [comment]
Ok, this was the fastest self-closing issue ever :

In order to work, with your package, the `docker-compose.yml` have to container a `service` attribute :

```yaml
services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
...
```
