### ISSUE TITLE
Multiple compose files

### ISSUE THREAD

**Issue by cerdiogenes** [alanzanattadev/atom-docker#13]
When I try to add docker-compose.override.yml file I'm getting the following error:

```
YAMLException: duplicated mapping key at line 30, column 1:
    
    ^
```

Line 30 is the new line that atom inserts after saving the file.

My docker-compose.yml is:

```yml
version: '2'
services:
  worker:
    image: kdiogenes/fnix:worker
    command: bundle exec sidekiq -q mailers -q default
    volumes:
      - .:/var/www/fnix
      - bundle:/usr/local/bundle
    environment:
      REDIS_URL: 'redis://redis:6379'
  web:
    image: kdiogenes/fnix:web
    command: bundle exec guard --plugin foreman -i
    volumes:
      - .:/var/www/fnix
      - bundle:/usr/local/bundle
volumes:
  bundle:
```

And my docker-compose.override.yml is:
```yml
version: '2'
services:
  postgres:
    image: postgres
    command: -c fsync=off
    environment:
      POSTGRES_DB: fnix_development
  redis:
    image: redis
  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
  worker:
    build: .
    command: bundle exec sidekiq -q mailers -q default -L log/sidekiq.log
    links:
      - redis
  web:
    build: .
    command: bundle exec guard --plugin foreman annotate bundler -i
    user: "1000:1000"
    links:
      - mail
    ports:
      - "3000:3000"
    links:
      - postgres
      - worker
```

Thanks!
